import { getCompanyLogoBytes } from '@/lib/report-brand';
import {NextResponse} from 'next/server';import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';import {dbAdmin} from '@/lib/supabase';
function wrap(text:string,max=92){const words=String(text||'').split(/\s+/);const out:string[]=[];let line='';for(const w of words){if((line+' '+w).trim().length>max){out.push(line);line=w}else line=(line+' '+w).trim()}if(line)out.push(line);return out;}
export async function GET(_req:Request,{params}:{params:Promise<{token:string}>}){const {token}=await params;const db=dbAdmin();const {data:link}=await db.from('growth_intake_links').select('client_id').eq('token',token).in('status',['active','submitted']).maybeSingle();if(!link)return new NextResponse('Invalid link',{status:404});const {data:c}=await db.from('growth_clients').select('*').eq('id',link.client_id).single();const {data:s}=await db.from('growth_onboarding_state').select('*').eq('client_id',link.client_id).maybeSingle();const {data:a}=await db.from('growth_agreements').select('*').eq('client_id',link.client_id).order('created_at',{ascending:false}).limit(1).maybeSingle();const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const logo=await pdf.embedPng(getCompanyLogoBytes());let page=pdf.addPage([612,792]),y=690;const navy=rgb(.03,.09,.14),blue=rgb(.12,.55,.78),muted=rgb(.38,.47,.54);page.drawRectangle({x:0,y:706,width:612,height:86,color:navy});page.drawText('GROWTH INTELLIGENCE LLC',{x:36,y:772,size:9,font:bold,color:rgb(1,1,1)});page.drawText('CLIENT ONBOARDING RECORD',{x:36,y:752,size:10,font:bold,color:rgb(1,1,1)});page.drawText(c?.business_name||'Client',{x:36,y:731,size:14,lineHeight:16,maxWidth:380,font:bold,color:rgb(1,1,1)});page.drawImage(logo,{x:454,y:713,width:108,height:72});y=686;
function line(t:string,size=9,b=false,color=rgb(.08,.14,.2)){for(const l of wrap(t,size>12?70:94)){if(y<55){page=pdf.addPage([612,792]);y=740}page.drawText(l,{x:40,y,size,font:b?bold:regular,color});y-=size+4}}
function section(t:string){y-=8;line(t,13,true,blue);y-=3}
section('Program');line(`Initial term: 90 days | Management: $${Number(c?.management_fee||0).toLocaleString()}/month | Google media recommendation: $${Number(c?.ad_budget||0).toLocaleString()}/month | Setup: $${Number(c?.setup_fee||0).toLocaleString()}`);
section('Business Intake');const business=s?.payload?.business||{};for(const [k,v] of Object.entries(business)){line(`${String(k).replaceAll('_',' ')}: ${String(v)}`,9,false)}
section('System Access Plan');const access=s?.payload?.access||{};for(const [k,v] of Object.entries(access)){line(`${k}: ${String(v)}`,9,false)}
section('Agreement');line(`Accepted: ${a?.accepted?'Yes':'No'} | Signer: ${a?.signer_name||''} | Title: ${a?.signer_title||''} | Signed: ${a?.signed_at?new Date(a.signed_at).toLocaleString():''}`);line('Client-owned Google, website, domain, analytics and advertising accounts remain Client property. Growth Intelligence LLC receives delegated access for the approved scope. Specific rankings, lead counts, revenue, and return on ad spend are not guaranteed.',8,false,muted);
section('Submission');line(`Onboarding status: ${c?.onboarding_status||''} | Program status: ${c?.status||''} | Generated: ${new Date().toLocaleString()}`);
const bytes=await pdf.save();const safe=String(c?.business_name||'Client').replace(/[^a-z0-9]+/gi,'_');return new NextResponse(new Uint8Array(bytes),{headers:{'content-type':'application/pdf','content-disposition':`attachment; filename="${safe}_Onboarding_Record.pdf"`,'cache-control':'private, no-store'}})}
