import {dbAdmin} from '@/lib/supabase';
import {industryThemes} from '@/lib/industry';
import {notFound} from 'next/navigation';

const steps=[['analysis','Analysis'],['program','Program'],['business','Business'],['access','Access'],['agreement','Agreement'],['review','Review'],['complete','Activation']];
const accessPlatforms=['Google Business Profile','Google Ads','Google Analytics 4','Google Search Console','Google Tag Manager','Website Admin','Domain / DNS'];
function money(v:any){return `$${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0})}`}
function stepIndex(s:string){const i=steps.findIndex(x=>x[0]===s);return i<0?0:i}

export default async function Portal({params,searchParams}:{params:Promise<{token:string}>,searchParams:Promise<{step?:string}>}){
  const {token}=await params;const q=await searchParams;const db=dbAdmin();
  const {data:link}=await db.from('growth_intake_links').select('*').eq('token',token).in('status',['active','submitted']).maybeSingle();if(!link)notFound();
  const {data:c}=await db.from('growth_clients').select('*').eq('id',link.client_id).single();if(!c)notFound();
  const {data:run}=await db.from('growth_analysis_runs').select('result_json,status').eq('client_id',c.id).order('created_at',{ascending:false}).limit(1).maybeSingle();
  const {data:state}=await db.from('growth_onboarding_state').select('*').eq('client_id',c.id).maybeSingle();
  const theme=industryThemes[c.industry]||industryThemes.general;const analysis=run?.result_json||{};const brand=c.brand_config||{};
  const requested=q.step||state?.current_step||'analysis';const step=c.onboarding_status==='complete'?'complete':requested;const idx=stepIndex(step);
  const primary=c.primary_color||theme.defaultPrimary;const accent=c.accent_color||theme.defaultAccent;
  const style={'--client-bg':primary,'--client-accent':accent} as React.CSSProperties;
  if(!c.portal_published){return <main className="portalPage" style={{...style,...(brand.hero_image?{backgroundImage:`linear-gradient(180deg,rgba(2,8,13,.58),rgba(2,8,13,.94)),url(${brand.hero_image})`,backgroundSize:'cover',backgroundPosition:'center top',backgroundAttachment:'fixed'}:{})}}><div className="portalWrap"><div className="portalHeader"><div className="portalBrandText">{c.business_name}</div><div className="powered">Prepared by RL Footage</div></div><section className="portalPanel center" style={{marginTop:80}}><div className="eyebrow">PRIVATE PORTAL PREPARING</div><h2>Your growth intelligence workspace is being finalized.</h2><p className="lead">RL Footage is reviewing the analysis before releasing it to your portal. Please return using this same secure link after your consultant confirms it is ready.</p></section></div></main>}
  return <main className="portalPage" style={{...style,...(brand.hero_image?{backgroundImage:`linear-gradient(180deg,rgba(2,8,13,.58),rgba(2,8,13,.94)),url(${brand.hero_image})`,backgroundSize:'cover',backgroundPosition:'center top',backgroundAttachment:'fixed'}:{})}}><div className="portalWrap">
    <header className="portalHeader"><div>{c.logo_url?<img className="portalLogo" src={c.logo_url} alt={`${c.business_name} logo`}/>:<div className="portalBrandText">{c.business_name}</div>}</div><div className="powered">Private Growth Intelligence Portal • RL Footage</div></header>
    <section className="portalHero"><div className="eyebrow">{theme.label.toUpperCase()} • PREPARED EXCLUSIVELY FOR {String(c.business_name).toUpperCase()}</div><h1>{analysis.brand?.portal_headline||'Your Google Growth Program'}</h1><p>One guided step at a time. Review what we found, understand the 90-day treatment plan, confirm your program, complete the private business intake, connect the systems we need, sign the agreement, and activate your account.</p></section>
    <nav className="portalSteps">{steps.map(([key,label],i)=><div key={key} className={`portalStep ${i===idx?'on':''} ${i<idx?'done':''}`}><span>{String(i+1).padStart(2,'0')}</span><b>{label}</b></div>)}</nav>

    {step==='analysis'&&<section className="portalPanel"><div className="eyebrow">STEP 01 • YOUR BUSINESS INTELLIGENCE</div><h2>We studied your digital position before asking you to move forward.</h2><p className="lead">Our research engine reviewed the public footprint of {c.business_name}, its website, search relevance, reputation, local competition, conversion path and paid-search opportunity. The reports below are built from the same evidence record.</p>
      <div className="reportCards"><article className="reportCard"><div className="tag">REPORT 01</div><h3>Google Growth Audit</h3><p>What is working, what is weak, competitor/reputation context, SEO and website issues, local visibility opportunity and paid-search direction.</p><a className="portalBtn" href={`/api/reports/${c.id}/audit?token=${token}`}>Open Audit PowerPoint</a></article><article className="reportCard"><div className="tag">REPORT 02</div><h3>90-Day Treatment Roadmap</h3><p>What RL Footage will do, in order, why each treatment is being applied and how improvement will be measured.</p><a className="portalBtn" href={`/api/reports/${c.id}/roadmap?token=${token}`}>Open Roadmap PowerPoint</a></article></div>
      <div className="portalActions"><span className="muted small">You can return to both reports anytime using this secure portal.</span><a className="portalBtn" href={`/p/${token}?step=program`}>Continue to Your Program →</a></div></section>}

    {step==='program'&&<section className="portalPanel"><div className="eyebrow">STEP 02 • YOUR RECOMMENDED PROGRAM</div><h2>Your growth program and commercial terms.</h2><p className="lead">This is the operating program RL Footage will use to move from the audit findings into implementation, measurement and ongoing optimization.</p>
      <div className="priceBox"><div className="priceCell"><div className="label">Program</div><strong>Google Growth Management</strong><div className="small muted">SEO • Local Search • Google Business • Google Ads Management • Conversion Tracking • Reviews • Reporting</div></div><div className="priceCell"><div className="label">Management</div><strong>{money(c.management_fee)}/mo</strong></div><div className="priceCell"><div className="label">Recommended Google Media</div><strong>{money(c.ad_budget)}/mo</strong></div></div>
      {Number(c.setup_fee||0)>0&&<div className="checkItem"><div className="checkIcon">✓</div>One-time onboarding / setup fee: <b>{money(c.setup_fee)}</b></div>}
      <div className="checkGrid" style={{marginTop:16}}>{['Google Business Profile management','Local SEO & technical/on-page optimization','Google Ads audit, campaign structure & optimization','Conversion / call / form measurement','Review & reputation workflow','Monthly performance and strategy review'].map(x=><div className="checkItem" key={x}><div className="checkIcon">✓</div>{x}</div>)}</div>
      <div className="portalActions"><a className="portalBtn secondary" href={`/p/${token}?step=analysis`}>← Back</a><a className="portalBtn" href={`/p/${token}?step=business`}>Continue to Business Intake →</a></div></section>}

    {step==='business'&&<section className="portalPanel"><div className="eyebrow">STEP 03 • PRIVATE BUSINESS INTAKE</div><h2>Help us understand what the public internet cannot tell us.</h2><p className="lead">This information refines the strategy around the services that actually make money, the areas you truly want to serve and the capacity your team can support.</p>
      <form action={`/api/portal/${token}/save`} method="post"><input type="hidden" name="step" value="business"/><div className="formGrid">
        <label className="field"><div className="fieldLabel">Primary Business Phone</div><input name="phone" defaultValue={state?.payload?.business?.phone||c.phone||''} required/></label>
        <label className="field"><div className="fieldLabel">Business / Service Base</div><input name="address" defaultValue={state?.payload?.business?.address||c.address||''}/></label>
        <label className="field"><div className="fieldLabel">Priority Cities / Areas</div><textarea name="priority_cities" defaultValue={state?.payload?.business?.priority_cities||''} placeholder="Cities where you want the most growth"/></label>
        <label className="field"><div className="fieldLabel">Areas to Exclude</div><textarea name="excluded_areas" defaultValue={state?.payload?.business?.excluded_areas||''} placeholder="Areas you do not want to advertise"/></label>
        <label className="field"><div className="fieldLabel">Highest-Profit Services</div><textarea name="highest_profit_services" defaultValue={state?.payload?.business?.highest_profit_services||''} placeholder="Which services make you the most money? Include average job values if possible." required/></label>
        <label className="field"><div className="fieldLabel">Services We Should Push First</div><textarea name="priority_services" defaultValue={state?.payload?.business?.priority_services||''} placeholder="If we could create more of 3 services, what would you choose?" required/></label>
        <label className="field"><div className="fieldLabel">Current Capacity</div><textarea name="capacity" defaultValue={state?.payload?.business?.capacity||''} placeholder="Technicians, trucks, calls/jobs per week, after-hours availability"/></label>
        <label className="field"><div className="fieldLabel">Previous Marketing Problems</div><textarea name="marketing_history" defaultValue={state?.payload?.business?.marketing_history||''} placeholder="What happened with previous SEO / Google Ads companies? What did you dislike?"/></label>
        <label className="field"><div className="fieldLabel">Who Answers New Leads?</div><input name="lead_handler" defaultValue={state?.payload?.business?.lead_handler||''}/></label>
        <label className="field"><div className="fieldLabel">What Does Success Look Like in 90 Days?</div><input name="goals" defaultValue={state?.payload?.business?.goals||''}/></label>
      </div><div className="portalActions"><a className="portalBtn secondary" href={`/p/${token}?step=program`}>← Back</a><button className="portalBtn">Save & Continue →</button></div></form></section>}

    {step==='access'&&<section className="portalPanel"><div className="eyebrow">STEP 04 • SYSTEM ACCESS</div><h2>Connect the systems required for implementation.</h2><p className="lead">Do not send passwords, verification codes or recovery codes. Give RL Footage delegated access through each platform whenever possible. This keeps ownership with your business and lets access be revoked later.</p>
      <form action={`/api/portal/${token}/save`} method="post"><input type="hidden" name="step" value="access"/><div className="checkGrid">{accessPlatforms.map((x,i)=><label className="field" key={x}><div className="fieldLabel">{x}</div><select name={`access_${i}`} defaultValue={state?.payload?.access?.[`access_${i}`]||'ready'}><option value="ready">Ready to grant access</option><option value="granted">Access already granted</option><option value="need_setup">We do not have this / RL Footage should set it up</option><option value="not_applicable">Not applicable</option></select><div className="hint">{x.includes('Google')?'Use Google user/manager permissions — never share the account password.':'RL Footage will confirm the safest access method during kickoff.'}</div></label>)}</div>
      <div className="signatureBox" style={{marginTop:16}}><b>Historical marketing files (optional but valuable)</b><p className="small muted">Please have previous SEO reports, Google Ads reports, call tracking reports or lead spreadsheets ready for the kickoff review. File upload/storage will be available in the active client workspace.</p></div>
      <div className="portalActions"><a className="portalBtn secondary" href={`/p/${token}?step=business`}>← Back</a><button className="portalBtn">Save Access Plan & Continue →</button></div></form></section>}

    {step==='agreement'&&<section className="portalPanel"><div className="eyebrow">STEP 05 • AGREEMENT & AUTHORIZATION</div><h2>Review and authorize the 90-day program.</h2><p className="lead">The agreement below is generated from your approved program and pricing. Your core accounts remain owned by your business; RL Footage receives delegated access to perform the approved work.</p>
      <div className="signatureBox"><h3>Google Growth Marketing Services Agreement</h3><p className="small muted">Initial term: 90 days. Management: {money(c.management_fee)}/month. Recommended Google media budget: {money(c.ad_budget)}/month, paid by Client directly to Google. Setup fee: {money(c.setup_fee)}.</p><p className="small muted">Scope may include Google Business Profile management, local/technical/on-page SEO, service/location strategy, review workflow, Google Ads management, conversion tracking, landing-page optimization and monthly reporting. Search rankings, Maps placement, lead volume, revenue and return on ad spend are influenced by third-party platforms, competitors, demand and Client operations; no specific ranking, lead count or revenue is guaranteed. Client retains ownership of Client-owned Google, website, domain, analytics and advertising accounts. Client authorizes delegated access and routine optimization changes within the agreed scope. Media spend and third-party charges are separate from management fees.</p></div>
      <form action={`/api/portal/${token}/save`} method="post" style={{marginTop:18}}><input type="hidden" name="step" value="agreement"/><div className="formGrid"><label className="field"><div className="fieldLabel">Authorized Signer</div><input name="signer_name" defaultValue={state?.signature_name||`${c.first_name||''} ${c.last_name||''}`.trim()} required/></label><label className="field"><div className="fieldLabel">Title</div><input name="signer_title" defaultValue={state?.signature_title||''} placeholder="Owner / President / Authorized Representative" required/></label></div><label className="checkItem" style={{marginTop:12}}><input type="checkbox" name="accept" value="yes" required style={{width:18}}/> I have reviewed the program, pricing and agreement above and am authorized to accept it for {c.business_name}.</label><div className="portalActions"><a className="portalBtn secondary" href={`/p/${token}?step=access`}>← Back</a><button className="portalBtn">Sign & Continue →</button></div></form></section>}

    {step==='review'&&<section className="portalPanel"><div className="eyebrow">STEP 06 • FINAL REVIEW</div><h2>Everything is ready for activation.</h2><p className="lead">Your business strategy information, access plan and agreement have been recorded. Submit once to move the account into RL Footage's 48-hour strategy and implementation review.</p>
      <div className="checkGrid">{['Growth analysis reviewed','90-day roadmap reviewed','Program & pricing reviewed','Private business intake complete','System access plan complete','Agreement signed'].map(x=><div className="checkItem" key={x}><div className="checkIcon">✓</div>{x}</div>)}</div>
      <form action={`/api/portal/${token}/submit`} method="post"><div className="portalActions"><a className="portalBtn secondary" href={`/p/${token}?step=agreement`}>← Back</a><button className="portalBtn">Activate My Growth Program →</button></div></form></section>}

    {step==='complete'&&<section className="portalPanel center"><div className="completeOrb">✓</div><div className="eyebrow">ONBOARDING COMPLETE</div><h2>Your Growth Program Is Now Active</h2><p className="lead" style={{margin:'0 auto',maxWidth:720}}>RL Footage is now entering your <b>48-hour strategy and implementation review</b>. We will study the private business information you submitted, historical marketing information, connected-account availability and the public audit together. We will finalize the business-specific execution roadmap and begin the first approved tracking, Google visibility and technical adjustments. Our team will contact you to walk through the priorities and implementation details.</p><div className="reportCards" style={{textAlign:'left'}}><article className="reportCard"><div className="tag">NEXT 48 HOURS</div><h3>Strategy Refinement</h3><p>Public research is reconciled with the private service economics, territories, capacity and prior marketing history you provided.</p></article><article className="reportCard"><div className="tag">THEN</div><h3>Initial Implementation</h3><p>Tracking, access verification and the first approved Google/SEO corrections begin according to the treatment roadmap.</p></article></div><div className="portalActions" style={{justifyContent:'center'}}><a className="portalBtn secondary" href={`/api/reports/${c.id}/audit?token=${token}`}>Google Growth Audit</a><a className="portalBtn secondary" href={`/api/reports/${c.id}/roadmap?token=${token}`}>90-Day Roadmap</a><a className="portalBtn" href={`/api/portal/${token}/intake-pdf`}>Download Onboarding Record</a></div></section>}
  </div></main>
}
